name: go-build
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: build go
        # -v 显示编译的包
        run: go build -v .
      
      - name: test go
        # 运行当前目录和子目录下所有的测试
        run: go test -v ./...
      - name: upload binary file
        uses: actions/upload-artifact@v3.1.1
        with:
          path: go-github-action.exe
